const mongoose = require('mongoose');
const dotenv = require('dotenv');
const User = require('./models/User');
const TutorProfile = require('./models/TutorProfile');
const TutorReview = require('./models/TutorReview');

dotenv.config();

// ─── 50 realistic Nigerian tutor definitions ───────────────────────────────
const TUTORS = [
  // ── LAGOS (12) ─────────────────────────────────────────────────────────
  {
    name: 'Chidi Emmanuel Okafor',
    email: 'chidi.okafor@tutors.naijaandoverseas.com',
    phone: '+234 802 111 0001',
    headline: 'Top JAMB & WAEC Mathematics Tutor — 9 Years Experience',
    bio: 'I am a dedicated Mathematics and Physics tutor with 9 years of teaching experience. I have helped over 300 students score A in WAEC Mathematics and over 280 score above 300 in JAMB. My teaching method combines step-by-step problem solving with past question analysis. I make difficult topics easy to understand through real-life examples and structured practice. I am passionate about helping students build confidence in Science subjects.',
    subjects: ['Mathematics', 'Further Mathematics', 'Physics', 'JAMB Prep', 'WAEC Prep'],
    levels: ['sss', 'waec', 'jamb'],
    teachingMode: ['online', 'in-person'],
    state: 'Lagos',
    city: 'Lekki',
    hourlyRateNaira: 6000,
    groupRateNaira: 3500,
    trialAvailable: true,
    trialDurationMins: 30,
    yearsExperience: 9,
    languages: ['English', 'Igbo'],
    specializations: ['JAMB Preparation', 'WAEC Revision', 'Exam Time Management'],
    qualifications: [
      { title: 'B.Sc. Mathematics', institution: 'University of Lagos', year: '2014' },
      { title: 'PGDE (Post-Graduate Diploma in Education)', institution: 'University of Lagos', year: '2016' },
    ],
    rating: 4.9,
    reviewCount: 87,
    totalSessions: 312,
    isVerified: true,
    responseTime: 'Within 1 hour',
  },
  {
    name: 'Blessing Adaeze Nwosu',
    email: 'blessing.nwosu@tutors.naijaandoverseas.com',
    phone: '+234 803 111 0002',
    headline: 'English Language & Literature Expert — WAEC & JAMB Specialist',
    bio: 'I specialize in English Language and Literature in English for SS1–SS3 students preparing for WAEC and JAMB. With 6 years of experience, I have helped students improve their comprehension, essay writing, and oral English skills significantly. My sessions are engaging and interactive. I use a wide range of past questions and model essays to prepare students thoroughly for their exams.',
    subjects: ['English Language', 'Literature in English', 'Verbal Reasoning'],
    levels: ['jss', 'sss', 'waec', 'jamb'],
    teachingMode: ['online', 'in-person'],
    state: 'Lagos',
    city: 'Surulere',
    hourlyRateNaira: 4500,
    groupRateNaira: 2500,
    trialAvailable: true,
    trialDurationMins: 30,
    yearsExperience: 6,
    languages: ['English', 'Igbo'],
    specializations: ['WAEC Revision', 'JAMB Preparation', 'Essay Writing Coaching'],
    qualifications: [
      { title: 'B.A. English & Literary Studies', institution: 'University of Ibadan', year: '2017' },
    ],
    rating: 4.8,
    reviewCount: 62,
    totalSessions: 245,
    isVerified: true,
    responseTime: 'Within 1 hour',
  },
  {
    name: 'Tunde Kayode Adeyemi',
    email: 'tunde.adeyemi@tutors.naijaandoverseas.com',
    phone: '+234 804 111 0003',
    headline: 'Economics, Government & Commerce Tutor — 7 Years Experience',
    bio: 'I am an experienced Social Science tutor covering Economics, Government, and Commerce for SSS students. I break down complex economic theories and government processes into simple, relatable concepts. My students consistently score B2 and above in WAEC. I use current affairs, newspaper analysis, and past questions to make lessons practical and relevant.',
    subjects: ['Economics', 'Government', 'Commerce', 'WAEC Prep'],
    levels: ['sss', 'waec', 'jamb'],
    teachingMode: ['online'],
    state: 'Lagos',
    city: 'Ikeja',
    hourlyRateNaira: 3500,
    groupRateNaira: 2000,
    trialAvailable: true,
    trialDurationMins: 30,
    yearsExperience: 7,
    languages: ['English', 'Yoruba'],
    specializations: ['WAEC Revision', 'JAMB Preparation'],
    qualifications: [
      { title: 'B.Sc. Economics', institution: 'University of Lagos', year: '2015' },
    ],
    rating: 4.7,
    reviewCount: 54,
    totalSessions: 198,
    isVerified: true,
    responseTime: 'Within 3 hours',
  },
  {
    name: 'Chisom Adanna Obi',
    email: 'chisom.obi@tutors.naijaandoverseas.com',
    phone: '+234 805 111 0004',
    headline: 'Biology & Chemistry Expert — JAMB Score Booster',
    bio: 'I am a Life Sciences tutor specializing in Biology and Chemistry for SS2, SS3, and JAMB candidates. I have a unique approach to teaching organic chemistry and cell biology using diagrams and mnemonics that make topics stick. Over 200 of my students have scored A1 in WAEC Biology. I offer detailed past question walkthroughs every session.',
    subjects: ['Biology', 'Chemistry', 'Agricultural Science', 'JAMB Prep', 'WAEC Prep'],
    levels: ['sss', 'waec', 'jamb'],
    teachingMode: ['online'],
    state: 'Lagos',
    city: 'Victoria Island',
    hourlyRateNaira: 5000,
    groupRateNaira: 3000,
    trialAvailable: true,
    trialDurationMins: 30,
    yearsExperience: 5,
    languages: ['English', 'Igbo'],
    specializations: ['JAMB Preparation', 'WAEC Revision'],
    qualifications: [
      { title: 'B.Sc. Biochemistry', institution: 'University of Lagos', year: '2018' },
    ],
    rating: 4.9,
    reviewCount: 71,
    totalSessions: 267,
    isVerified: true,
    responseTime: 'Within 1 hour',
  },
  {
    name: 'Seun Michael Akinwale',
    email: 'seun.akinwale@tutors.naijaandoverseas.com',
    phone: '+234 806 111 0005',
    headline: 'Coding, Python & Computer Science Tutor — Tech Industry Expert',
    bio: 'I am a professional software developer with 8 years of industry experience who is passionate about teaching the next generation of Nigerian tech talents. I teach Python, Web Development (HTML/CSS/JavaScript), and Computer Science at both secondary and university levels. My sessions are hands-on — students build real projects from the first lesson. I have trained over 150 students who now work in tech companies.',
    subjects: ['Computer Science', 'Web Development', 'Python', 'Microsoft Office'],
    levels: ['sss', 'university', 'adult'],
    teachingMode: ['online'],
    state: 'Lagos',
    city: 'Yaba',
    hourlyRateNaira: 8000,
    groupRateNaira: 4500,
    trialAvailable: true,
    trialDurationMins: 45,
    yearsExperience: 8,
    languages: ['English', 'Yoruba'],
    specializations: ['Coding & Tech Skills'],
    qualifications: [
      { title: 'B.Sc. Computer Science', institution: 'University of Lagos', year: '2015' },
      { title: 'AWS Certified Developer', institution: 'Amazon Web Services', year: '2020' },
    ],
    rating: 5.0,
    reviewCount: 93,
    totalSessions: 340,
    isVerified: true,
    responseTime: 'Within 1 hour',
  },
  {
    name: 'Aisha Rauf Mohammed',
    email: 'aisha.mohammed@tutors.naijaandoverseas.com',
    phone: '+234 807 111 0006',
    headline: 'Primary & Junior Secondary Maths — Patience & Proven Results',
    bio: 'I am a highly patient and dedicated tutor for Primary School children and Junior Secondary students. I specialize in making Mathematics fun and easy for children who struggle with numbers. I use visual aids, games, and repetition techniques to build a strong foundation. Parents consistently report dramatic improvement in their children within 4–6 weeks of sessions with me.',
    subjects: ['Mathematics', 'Quantitative Reasoning', 'Verbal Reasoning', 'Basic Science'],
    levels: ['primary', 'jss'],
    teachingMode: ['in-person'],
    state: 'Lagos',
    city: 'Ojodu',
    hourlyRateNaira: 2500,
    groupRateNaira: 1500,
    trialAvailable: true,
    trialDurationMins: 30,
    yearsExperience: 4,
    languages: ['English', 'Hausa', 'Yoruba'],
    specializations: ['Common Entrance Prep'],
    qualifications: [
      { title: 'NCE (National Certificate of Education)', institution: 'Federal College of Education, Kano', year: '2019' },
    ],
    rating: 4.8,
    reviewCount: 45,
    totalSessions: 178,
    isVerified: true,
    responseTime: 'Within 3 hours',
  },
  {
    name: 'Kunle Babatunde Fashola',
    email: 'kunle.fashola@tutors.naijaandoverseas.com',
    phone: '+234 808 111 0007',
    headline: 'Further Maths & Physics Guru — University Lecturer Background',
    bio: 'I am a retired university lecturer with 15 years of teaching Further Mathematics and Physics at both secondary and tertiary levels. I provide comprehensive preparation for WAEC, JAMB, and NECO with a structured curriculum. My teaching methodology emphasizes deep understanding over rote memorization. Students who attend my classes consistently score A1 in Further Mathematics.',
    subjects: ['Further Mathematics', 'Mathematics', 'Physics', 'JAMB Prep', 'WAEC Prep'],
    levels: ['sss', 'waec', 'jamb', 'neco', 'university'],
    teachingMode: ['online', 'in-person'],
    state: 'Lagos',
    city: 'Gbagada',
    hourlyRateNaira: 5500,
    groupRateNaira: 3000,
    trialAvailable: true,
    trialDurationMins: 30,
    yearsExperience: 15,
    languages: ['English', 'Yoruba'],
    specializations: ['WAEC Revision', 'JAMB Preparation', 'Post-UTME Coaching'],
    qualifications: [
      { title: 'M.Sc. Applied Mathematics', institution: 'University of Lagos', year: '2008' },
      { title: 'B.Sc. Mathematics', institution: 'Obafemi Awolowo University', year: '2005' },
    ],
    rating: 4.9,
    reviewCount: 110,
    totalSessions: 428,
    isVerified: true,
    responseTime: 'Within 3 hours',
  },
  {
    name: 'Jennifer Adeyemi Olatunji',
    email: 'jennifer.olatunji@tutors.naijaandoverseas.com',
    phone: '+234 809 111 0008',
    headline: 'IELTS & TOEFL Coach — 8.0 Band Score Specialist',
    bio: 'I am a British Council-certified IELTS coach and English language expert. I have helped over 500 Nigerian students achieve their target band scores (6.5–8.0) for UK, Canada, Australia, and USA university admissions. My sessions cover all four IELTS modules: Reading, Writing, Listening, and Speaking, with targeted practice for each. I provide personalized feedback and mock tests every week.',
    subjects: ['IELTS', 'TOEFL', 'English Language', 'SAT'],
    levels: ['sss', 'university', 'adult'],
    teachingMode: ['online'],
    state: 'Lagos',
    city: 'Lekki',
    hourlyRateNaira: 10000,
    groupRateNaira: 6000,
    trialAvailable: true,
    trialDurationMins: 45,
    yearsExperience: 10,
    languages: ['English'],
    specializations: ['IELTS Coaching', 'TOEFL Preparation'],
    qualifications: [
      { title: 'M.A. Linguistics', institution: 'University of Lagos', year: '2013' },
      { title: 'British Council IELTS Examiner Certification', institution: 'British Council Nigeria', year: '2015' },
    ],
    rating: 4.9,
    reviewCount: 142,
    totalSessions: 520,
    isVerified: true,
    responseTime: 'Within 1 hour',
  },
  {
    name: 'Emeka Chukwu Onuoha',
    email: 'emeka.onuoha@tutors.naijaandoverseas.com',
    phone: '+234 810 111 0009',
    headline: 'Chemistry & Biology Made Simple — WAEC Expert',
    bio: 'I specialize in breaking down difficult Chemistry and Biology topics for SS1–SS3 students. With 5 years of tutoring experience, I have developed unique study notes and past question banks that help students revise efficiently. I offer both online and home sessions across Lagos. My class sizes are small to ensure every student gets individual attention.',
    subjects: ['Chemistry', 'Biology', 'Agricultural Science', 'WAEC Prep'],
    levels: ['sss', 'waec', 'neco'],
    teachingMode: ['online', 'in-person'],
    state: 'Lagos',
    city: 'Agege',
    hourlyRateNaira: 3500,
    groupRateNaira: 2000,
    trialAvailable: true,
    trialDurationMins: 30,
    yearsExperience: 5,
    languages: ['English', 'Igbo'],
    specializations: ['WAEC Revision', 'NECO Preparation'],
    qualifications: [
      { title: 'B.Sc. Chemistry', institution: 'University of Port Harcourt', year: '2018' },
    ],
    rating: 4.6,
    reviewCount: 48,
    totalSessions: 185,
    isVerified: true,
    responseTime: 'Within 3 hours',
  },
  {
    name: 'Damilola Adeola Williams',
    email: 'damilola.williams@tutors.naijaandoverseas.com',
    phone: '+234 811 111 0010',
    headline: 'Primary School Specialist — Phonics, Maths & Common Entrance',
    bio: 'I am passionate about helping young children build a strong academic foundation. I teach Primary 1 to Primary 6 pupils with a focus on making learning fun. I specialize in Common Entrance preparation for Lagos State and federal government schools. I use colourful materials, educational games, and child-friendly techniques to make lessons enjoyable.',
    subjects: ['Mathematics', 'English Language', 'Quantitative Reasoning', 'Verbal Reasoning', 'Phonics & Reading', 'Basic Science'],
    levels: ['primary'],
    teachingMode: ['in-person'],
    state: 'Lagos',
    city: 'Ajah',
    hourlyRateNaira: 2000,
    groupRateNaira: 1200,
    trialAvailable: true,
    trialDurationMins: 30,
    yearsExperience: 3,
    languages: ['English', 'Yoruba'],
    specializations: ['Common Entrance Prep'],
    qualifications: [
      { title: 'B.Ed. Early Childhood Education', institution: 'Lagos State University', year: '2020' },
    ],
    rating: 4.8,
    reviewCount: 36,
    totalSessions: 142,
    isVerified: false,
    responseTime: 'Within 24 hours',
  },
  {
    name: 'Ifeanyi Patrick Nze',
    email: 'ifeanyi.nze@tutors.naijaandoverseas.com',
    phone: '+234 812 111 0011',
    headline: 'Physics & Further Maths Online Tutor — JAMB 340+ Results',
    bio: 'I am an online Physics and Further Mathematics tutor with a track record of helping students score 300+ in JAMB. My approach focuses on understanding concepts deeply before attempting past questions. I provide detailed notes, video explanations, and unlimited follow-up support between sessions. My online classes run on Zoom with shared screen and digital whiteboard.',
    subjects: ['Physics', 'Further Mathematics', 'Mathematics', 'JAMB Prep'],
    levels: ['sss', 'jamb', 'waec'],
    teachingMode: ['online'],
    state: 'Lagos',
    city: 'Oshodi',
    hourlyRateNaira: 4000,
    groupRateNaira: 2200,
    trialAvailable: true,
    trialDurationMins: 30,
    yearsExperience: 4,
    languages: ['English', 'Igbo'],
    specializations: ['JAMB Preparation', 'Post-UTME Coaching'],
    qualifications: [
      { title: 'B.Eng. Electrical & Electronics Engineering', institution: 'University of Lagos', year: '2019' },
    ],
    rating: 4.7,
    reviewCount: 59,
    totalSessions: 231,
    isVerified: true,
    responseTime: 'Within 1 hour',
  },
  {
    name: 'Bola Adekunle Adekoya',
    email: 'bola.adekoya@tutors.naijaandoverseas.com',
    phone: '+234 813 111 0012',
    headline: 'Government, History & CRS Tutor — Engaging & Fun Lessons',
    bio: 'I make Government, History, and Christian Religious Studies interesting through storytelling, current affairs, and debates. Students who were previously bored by these subjects often become their class leaders after a few sessions. I prepare students thoroughly for WAEC and NECO with a deep dive into past questions, marking guides, and model answers.',
    subjects: ['Government', 'History', 'Christian Religious Studies', 'Civic Education'],
    levels: ['jss', 'sss', 'waec', 'neco'],
    teachingMode: ['online', 'in-person'],
    state: 'Lagos',
    city: 'Badagry',
    hourlyRateNaira: 3000,
    groupRateNaira: 1800,
    trialAvailable: true,
    trialDurationMins: 30,
    yearsExperience: 6,
    languages: ['English', 'Yoruba'],
    specializations: ['WAEC Revision', 'NECO Preparation'],
    qualifications: [
      { title: 'B.A. History & Strategic Studies', institution: 'University of Lagos', year: '2016' },
    ],
    rating: 4.5,
    reviewCount: 41,
    totalSessions: 165,
    isVerified: true,
    responseTime: 'Within 3 hours',
  },

  // ── ABUJA / FCT (8) ─────────────────────────────────────────────────────
  {
    name: 'Fatima Aliyu Yusuf',
    email: 'fatima.yusuf@tutors.naijaandoverseas.com',
    phone: '+234 802 222 0013',
    headline: 'Mathematics & Physics Tutor in Abuja — 8 Years Experience',
    bio: 'I am a trained mathematics and physics teacher with 8 years of experience teaching in top Abuja schools. I now offer private tutoring for SSS students and JAMB candidates across FCT. I focus on building problem-solving skills through structured practice and past question analysis. My students have consistently excelled in WAEC and JAMB.',
    subjects: ['Mathematics', 'Physics', 'JAMB Prep', 'WAEC Prep', 'Further Mathematics'],
    levels: ['sss', 'waec', 'jamb'],
    teachingMode: ['online', 'in-person'],
    state: 'FCT',
    city: 'Garki',
    hourlyRateNaira: 4500,
    groupRateNaira: 2500,
    trialAvailable: true,
    trialDurationMins: 30,
    yearsExperience: 8,
    languages: ['English', 'Hausa'],
    specializations: ['JAMB Preparation', 'WAEC Revision'],
    qualifications: [
      { title: 'B.Sc. Physics', institution: 'Ahmadu Bello University', year: '2014' },
      { title: 'PGDE', institution: 'University of Abuja', year: '2016' },
    ],
    rating: 4.8,
    reviewCount: 76,
    totalSessions: 290,
    isVerified: true,
    responseTime: 'Within 1 hour',
  },
  {
    name: 'Ibrahim Musa Tanko',
    email: 'ibrahim.tanko@tutors.naijaandoverseas.com',
    phone: '+234 803 222 0014',
    headline: 'Chemistry & Biology Specialist — A1 Guarantee Approach',
    bio: 'I have been teaching Chemistry and Biology for 7 years with a consistent record of helping students achieve A1 in WAEC. I use a topic-by-topic systematic approach combined with intensive past question practice. Online sessions are conducted via Zoom with PDF notes shared after each class. I also offer holiday crash courses.',
    subjects: ['Chemistry', 'Biology', 'WAEC Prep', 'NECO Prep'],
    levels: ['sss', 'waec', 'neco', 'jamb'],
    teachingMode: ['online'],
    state: 'FCT',
    city: 'Wuse',
    hourlyRateNaira: 4000,
    groupRateNaira: 2200,
    trialAvailable: true,
    trialDurationMins: 30,
    yearsExperience: 7,
    languages: ['English', 'Hausa'],
    specializations: ['WAEC Revision', 'NECO Preparation', 'JAMB Preparation'],
    qualifications: [
      { title: 'B.Sc. Chemistry', institution: 'Ahmadu Bello University', year: '2015' },
    ],
    rating: 4.7,
    reviewCount: 64,
    totalSessions: 253,
    isVerified: true,
    responseTime: 'Within 3 hours',
  },
  {
    name: 'Chiamaka Nneka Obi',
    email: 'chiamaka.obi@tutors.naijaandoverseas.com',
    phone: '+234 804 222 0015',
    headline: 'English, Literature & Verbal Reasoning — All Levels Welcome',
    bio: 'I am an English Language teacher and certified literacy specialist. I offer tutoring for all levels — from Primary school pupils improving reading comprehension to SS3 students preparing for WAEC English. My methods are communication-focused; I build students\' confidence in speaking and writing through fun activities, debates, and creative exercises.',
    subjects: ['English Language', 'Literature in English', 'Verbal Reasoning', 'Phonics & Reading'],
    levels: ['primary', 'jss', 'sss', 'waec'],
    teachingMode: ['in-person'],
    state: 'FCT',
    city: 'Asokoro',
    hourlyRateNaira: 5000,
    groupRateNaira: 3000,
    trialAvailable: true,
    trialDurationMins: 30,
    yearsExperience: 9,
    languages: ['English', 'Igbo'],
    specializations: ['WAEC Revision', 'Common Entrance Prep'],
    qualifications: [
      { title: 'M.A. English Language', institution: 'University of Nigeria, Nsukka', year: '2014' },
    ],
    rating: 4.9,
    reviewCount: 88,
    totalSessions: 345,
    isVerified: true,
    responseTime: 'Within 1 hour',
  },
  {
    name: 'Aminu Garba Suleiman',
    email: 'aminu.suleiman@tutors.naijaandoverseas.com',
    phone: '+234 805 222 0016',
    headline: 'Further Mathematics Specialist — Distinction Level Results',
    bio: 'I am one of Abuja\'s top Further Mathematics tutors with a strong background in advanced calculus, statistics, and mechanics. I prepare SS2 and SS3 students for WAEC and also support first-year university students struggling with calculus. My structured notes and video walkthroughs have helped many students achieve distinctions.',
    subjects: ['Further Mathematics', 'Mathematics', 'Physics', 'JAMB Prep'],
    levels: ['sss', 'waec', 'jamb', 'university'],
    teachingMode: ['online', 'in-person'],
    state: 'FCT',
    city: 'Maitama',
    hourlyRateNaira: 5500,
    groupRateNaira: 3000,
    trialAvailable: true,
    trialDurationMins: 30,
    yearsExperience: 10,
    languages: ['English', 'Hausa'],
    specializations: ['JAMB Preparation', 'WAEC Revision', 'Post-UTME Coaching'],
    qualifications: [
      { title: 'M.Sc. Mathematics', institution: 'Ahmadu Bello University', year: '2013' },
    ],
    rating: 4.8,
    reviewCount: 95,
    totalSessions: 380,
    isVerified: true,
    responseTime: 'Within 1 hour',
  },
  {
    name: 'Stella Agada Onah',
    email: 'stella.onah@tutors.naijaandoverseas.com',
    phone: '+234 806 222 0017',
    headline: 'Economics & Financial Accounting Tutor — Business Education Expert',
    bio: 'I am a Business Education specialist with 7 years of tutoring experience in Economics, Financial Accounting, and Commerce. My sessions are application-oriented — I help students connect classroom theory to real business situations. Students who have previously failed Accounting in school often achieve B3 or above after working with me.',
    subjects: ['Economics', 'Financial Accounting', 'Commerce', 'WAEC Prep'],
    levels: ['sss', 'waec', 'neco'],
    teachingMode: ['online'],
    state: 'FCT',
    city: 'Gwarinpa',
    hourlyRateNaira: 3500,
    groupRateNaira: 2000,
    trialAvailable: true,
    trialDurationMins: 30,
    yearsExperience: 7,
    languages: ['English', 'Igbo'],
    specializations: ['WAEC Revision'],
    qualifications: [
      { title: 'B.Sc. Accounting', institution: 'University of Nigeria, Nsukka', year: '2015' },
    ],
    rating: 4.6,
    reviewCount: 52,
    totalSessions: 204,
    isVerified: true,
    responseTime: 'Within 3 hours',
  },
  {
    name: 'Felix Okoro Ugwu',
    email: 'felix.ugwu@tutors.naijaandoverseas.com',
    phone: '+234 807 222 0018',
    headline: 'Python, Web Dev & Data Science Tutor — Real Projects Focus',
    bio: 'I am a full-stack developer and data scientist who teaches programming to students of all backgrounds. My courses cover Python basics to data analysis with Pandas, and Web Development from HTML to ReactJS. I believe in learning by doing — every student builds a portfolio project during our sessions. I also prepare university students for technical interviews.',
    subjects: ['Python', 'Web Development', 'Computer Science', 'Microsoft Office'],
    levels: ['sss', 'university', 'adult'],
    teachingMode: ['online'],
    state: 'FCT',
    city: 'Kubwa',
    hourlyRateNaira: 7000,
    groupRateNaira: 4000,
    trialAvailable: true,
    trialDurationMins: 45,
    yearsExperience: 6,
    languages: ['English', 'Igbo'],
    specializations: ['Coding & Tech Skills'],
    qualifications: [
      { title: 'B.Sc. Computer Science', institution: 'University of Nigeria, Nsukka', year: '2017' },
      { title: 'Google Data Analytics Certificate', institution: 'Google / Coursera', year: '2021' },
    ],
    rating: 4.9,
    reviewCount: 78,
    totalSessions: 299,
    isVerified: true,
    responseTime: 'Within 1 hour',
  },
  {
    name: 'Halima Sadau Musa',
    email: 'halima.musa@tutors.naijaandoverseas.com',
    phone: '+234 808 222 0019',
    headline: 'Primary School & JSS Home Tutor — Abuja Area',
    bio: 'I offer home tutoring for Primary and Junior Secondary school pupils in the Abuja area. I am patient, kind, and very experienced with young learners. I teach all core primary school subjects and specialize in helping children with learning challenges. I work closely with parents to track each child\'s progress and tailor lessons to their individual needs.',
    subjects: ['Mathematics', 'English Language', 'Basic Science', 'Social Studies', 'Quantitative Reasoning', 'Verbal Reasoning'],
    levels: ['primary', 'jss'],
    teachingMode: ['in-person'],
    state: 'FCT',
    city: 'Karu',
    hourlyRateNaira: 2000,
    groupRateNaira: 1200,
    trialAvailable: true,
    trialDurationMins: 30,
    yearsExperience: 5,
    languages: ['English', 'Hausa'],
    specializations: ['Common Entrance Prep'],
    qualifications: [
      { title: 'NCE Primary Education', institution: 'FCE Zaria', year: '2018' },
    ],
    rating: 4.7,
    reviewCount: 39,
    totalSessions: 155,
    isVerified: false,
    responseTime: 'Within 24 hours',
  },
  {
    name: 'Wisdom Chidi Ikenna',
    email: 'wisdom.ikenna@tutors.naijaandoverseas.com',
    phone: '+234 809 222 0020',
    headline: 'JAMB & WAEC Crash Course Specialist — 6-Week Programme',
    bio: 'I offer intensive JAMB and WAEC preparation using a proven 6-week crash course programme. I cover Mathematics, English, and one Science subject of your choice. My programme includes daily practice questions, weekly mock exams, and performance reports for parents. Over 90% of my students have scored 250+ in JAMB. I teach both online and in-person in the Lugbe/Abuja area.',
    subjects: ['Mathematics', 'English Language', 'Physics', 'Chemistry', 'JAMB Prep', 'WAEC Prep'],
    levels: ['sss', 'waec', 'jamb'],
    teachingMode: ['online', 'in-person'],
    state: 'FCT',
    city: 'Lugbe',
    hourlyRateNaira: 5000,
    groupRateNaira: 2800,
    trialAvailable: true,
    trialDurationMins: 30,
    yearsExperience: 5,
    languages: ['English', 'Igbo'],
    specializations: ['JAMB Preparation', 'WAEC Revision', 'Exam Time Management'],
    qualifications: [
      { title: 'B.Sc. Education Mathematics', institution: 'University of Abuja', year: '2019' },
    ],
    rating: 4.8,
    reviewCount: 67,
    totalSessions: 258,
    isVerified: true,
    responseTime: 'Within 3 hours',
  },

  // ── KANO / NORTH (6) ────────────────────────────────────────────────────
  {
    name: 'Usman Abdullahi Yakubu',
    email: 'usman.yakubu@tutors.naijaandoverseas.com',
    phone: '+234 802 333 0021',
    headline: 'Mathematics, Physics & Chemistry — Kano\'s Best Tutor',
    bio: 'I am a Science teacher and private tutor with 10 years of experience in Kano State. I teach SS students preparing for WAEC, NECO, and JAMB with a focus on building solid foundations in Mathematics, Physics, and Chemistry. I am patient, methodical, and results-oriented. Home and centre-based classes are available across Kano.',
    subjects: ['Mathematics', 'Physics', 'Chemistry', 'WAEC Prep', 'NECO Prep', 'JAMB Prep'],
    levels: ['jss', 'sss', 'waec', 'neco', 'jamb'],
    teachingMode: ['online', 'in-person'],
    state: 'Kano',
    city: 'Kano',
    hourlyRateNaira: 2500,
    groupRateNaira: 1500,
    trialAvailable: true,
    trialDurationMins: 30,
    yearsExperience: 10,
    languages: ['English', 'Hausa'],
    specializations: ['WAEC Revision', 'JAMB Preparation', 'NECO Preparation'],
    qualifications: [
      { title: 'B.Sc. Physics', institution: 'Bayero University Kano', year: '2013' },
    ],
    rating: 4.8,
    reviewCount: 80,
    totalSessions: 320,
    isVerified: true,
    responseTime: 'Within 3 hours',
  },
  {
    name: 'Aisha Yusuf Umar',
    email: 'aisha.umar@tutors.naijaandoverseas.com',
    phone: '+234 803 333 0022',
    headline: 'English Language & Hausa Tutor — All Ages Welcome',
    bio: 'I am an English and Hausa language teacher with 8 years of experience across primary and secondary schools in Kano. I help students improve their communication skills in both English and Hausa. For exam students, I focus on WAEC English comprehension, essay writing, and Hausa language papers. I am very patient with young learners.',
    subjects: ['English Language', 'Hausa', 'Verbal Reasoning', 'Literature in English'],
    levels: ['primary', 'jss', 'sss', 'waec'],
    teachingMode: ['in-person'],
    state: 'Kano',
    city: 'Kano',
    hourlyRateNaira: 2000,
    groupRateNaira: 1200,
    trialAvailable: true,
    trialDurationMins: 30,
    yearsExperience: 8,
    languages: ['English', 'Hausa'],
    specializations: ['WAEC Revision'],
    qualifications: [
      { title: 'B.A. English & French', institution: 'Bayero University Kano', year: '2014' },
    ],
    rating: 4.6,
    reviewCount: 44,
    totalSessions: 176,
    isVerified: true,
    responseTime: 'Within 24 hours',
  },
  {
    name: 'Musa Sani Aliyu',
    email: 'musa.aliyu@tutors.naijaandoverseas.com',
    phone: '+234 804 333 0023',
    headline: 'Economics, Government & Commerce Online Tutor — Kaduna',
    bio: 'I teach Social Sciences and Business subjects online to SS students across Northern Nigeria. I am a qualified Economics teacher with 6 years of classroom experience. My online sessions are structured, well-paced, and examination-focused. I provide comprehensive notes, past question analysis, and individual performance tracking.',
    subjects: ['Economics', 'Government', 'Commerce', 'WAEC Prep', 'NECO Prep'],
    levels: ['sss', 'waec', 'neco'],
    teachingMode: ['online'],
    state: 'Kaduna',
    city: 'Kaduna',
    hourlyRateNaira: 2500,
    groupRateNaira: 1500,
    trialAvailable: true,
    trialDurationMins: 30,
    yearsExperience: 6,
    languages: ['English', 'Hausa'],
    specializations: ['WAEC Revision', 'NECO Preparation'],
    qualifications: [
      { title: 'B.Sc. Economics', institution: 'Ahmadu Bello University', year: '2016' },
    ],
    rating: 4.5,
    reviewCount: 37,
    totalSessions: 148,
    isVerified: true,
    responseTime: 'Within 24 hours',
  },
  {
    name: 'Bilkisu Ahmed Garba',
    email: 'bilkisu.garba@tutors.naijaandoverseas.com',
    phone: '+234 805 333 0024',
    headline: 'Biology & Chemistry Tutor — Katsina State',
    bio: 'I am a Biology and Chemistry teacher currently offering private tutoring in Katsina. My 5 years of teaching experience have given me deep insight into the common mistakes students make in these subjects. I use hands-on experiments (where possible) and colorful diagrams to teach difficult topics. I prepare students for both WAEC and NECO.',
    subjects: ['Biology', 'Chemistry', 'Agricultural Science', 'WAEC Prep', 'NECO Prep'],
    levels: ['sss', 'waec', 'neco'],
    teachingMode: ['online', 'in-person'],
    state: 'Katsina',
    city: 'Katsina',
    hourlyRateNaira: 2000,
    groupRateNaira: 1200,
    trialAvailable: true,
    trialDurationMins: 30,
    yearsExperience: 5,
    languages: ['English', 'Hausa'],
    specializations: ['WAEC Revision', 'NECO Preparation'],
    qualifications: [
      { title: 'B.Sc. Biology', institution: 'Usmanu Danfodiyo University Sokoto', year: '2018' },
    ],
    rating: 4.4,
    reviewCount: 28,
    totalSessions: 112,
    isVerified: false,
    responseTime: 'Within 24 hours',
  },
  {
    name: 'Mohammed Haruna Bello',
    email: 'mohammed.bello@tutors.naijaandoverseas.com',
    phone: '+234 806 333 0025',
    headline: 'Mathematics & Further Maths Online Tutor — Sokoto',
    bio: 'I am a passionate Mathematics tutor offering online classes to students across Nigeria from Sokoto. I specialize in SS2/SS3 Mathematics and Further Mathematics. My structured approach covers the full WAEC and JAMB syllabus systematically. Students receive detailed notes and practice sets after every session.',
    subjects: ['Mathematics', 'Further Mathematics', 'WAEC Prep', 'JAMB Prep'],
    levels: ['jss', 'sss', 'waec', 'jamb'],
    teachingMode: ['online'],
    state: 'Sokoto',
    city: 'Sokoto',
    hourlyRateNaira: 2500,
    groupRateNaira: 1400,
    trialAvailable: true,
    trialDurationMins: 30,
    yearsExperience: 4,
    languages: ['English', 'Hausa'],
    specializations: ['WAEC Revision', 'JAMB Preparation'],
    qualifications: [
      { title: 'B.Sc. Mathematics', institution: 'Usmanu Danfodiyo University Sokoto', year: '2019' },
    ],
    rating: 4.5,
    reviewCount: 31,
    totalSessions: 124,
    isVerified: true,
    responseTime: 'Within 24 hours',
  },
  {
    name: 'Zainab Suleiman Danjuma',
    email: 'zainab.danjuma@tutors.naijaandoverseas.com',
    phone: '+234 807 333 0026',
    headline: 'Mathematics & Physics In-Person Tutor — Bauchi State',
    bio: 'I offer home tutoring in Mathematics and Physics for JS3–SS3 students in Bauchi. I am an experienced and dedicated teacher who believes every student can excel with the right guidance. My lessons are interactive and tailored to each student\'s pace and learning style.',
    subjects: ['Mathematics', 'Physics', 'Basic Science', 'WAEC Prep'],
    levels: ['jss', 'sss', 'waec'],
    teachingMode: ['in-person'],
    state: 'Bauchi',
    city: 'Bauchi',
    hourlyRateNaira: 2000,
    groupRateNaira: 1200,
    trialAvailable: true,
    trialDurationMins: 30,
    yearsExperience: 3,
    languages: ['English', 'Hausa'],
    specializations: ['WAEC Revision'],
    qualifications: [
      { title: 'B.Sc. Physics Education', institution: 'Abubakar Tafawa Balewa University', year: '2021' },
    ],
    rating: 4.3,
    reviewCount: 19,
    totalSessions: 76,
    isVerified: false,
    responseTime: 'Within 24 hours',
  },

  // ── RIVERS / SOUTH-SOUTH (6) ─────────────────────────────────────────────
  {
    name: 'Ade Gabriel Tamuno',
    email: 'ade.tamuno@tutors.naijaandoverseas.com',
    phone: '+234 802 444 0027',
    headline: 'Chemistry, Further Maths & Maths — Port Harcourt\'s Finest',
    bio: 'I am a highly experienced Science and Mathematics tutor based in Port Harcourt with 12 years of teaching and tutoring experience. I have produced some of the highest WAEC and JAMB scores in Rivers State. My teaching style blends deep conceptual understanding with intensive practical drilling. I offer group and individual sessions.',
    subjects: ['Chemistry', 'Further Mathematics', 'Mathematics', 'Physics', 'JAMB Prep', 'WAEC Prep'],
    levels: ['sss', 'waec', 'jamb', 'neco'],
    teachingMode: ['online', 'in-person'],
    state: 'Rivers',
    city: 'Port Harcourt',
    hourlyRateNaira: 4500,
    groupRateNaira: 2500,
    trialAvailable: true,
    trialDurationMins: 30,
    yearsExperience: 12,
    languages: ['English'],
    specializations: ['JAMB Preparation', 'WAEC Revision', 'Post-UTME Coaching'],
    qualifications: [
      { title: 'M.Sc. Chemistry', institution: 'University of Port Harcourt', year: '2011' },
    ],
    rating: 4.9,
    reviewCount: 99,
    totalSessions: 395,
    isVerified: true,
    responseTime: 'Within 1 hour',
  },
  {
    name: 'Ebi Jessica Agbiti',
    email: 'ebi.agbiti@tutors.naijaandoverseas.com',
    phone: '+234 803 444 0028',
    headline: 'Biology & Chemistry Online Tutor — Exam Focused',
    bio: 'I am a Biology and Chemistry teacher offering online sessions for SS2 and SS3 students nationwide. I provide detailed topic-by-topic notes, past question solutions, and regular assessment tests. My approach is exam-focused and systematic. I also offer holiday crash courses for students preparing for WAEC.',
    subjects: ['Biology', 'Chemistry', 'Agricultural Science', 'WAEC Prep'],
    levels: ['sss', 'waec', 'neco'],
    teachingMode: ['online'],
    state: 'Rivers',
    city: 'Port Harcourt',
    hourlyRateNaira: 3500,
    groupRateNaira: 2000,
    trialAvailable: true,
    trialDurationMins: 30,
    yearsExperience: 5,
    languages: ['English'],
    specializations: ['WAEC Revision', 'NECO Preparation'],
    qualifications: [
      { title: 'B.Sc. Microbiology', institution: 'University of Port Harcourt', year: '2018' },
    ],
    rating: 4.6,
    reviewCount: 51,
    totalSessions: 203,
    isVerified: true,
    responseTime: 'Within 3 hours',
  },
  {
    name: 'Chukwudi Emeka Peters',
    email: 'chukwudi.peters@tutors.naijaandoverseas.com',
    phone: '+234 804 444 0029',
    headline: 'Physics & Mathematics — Online Classes Across Nigeria',
    bio: 'I offer online Physics and Mathematics classes for students across Nigeria from Yenagoa. My teaching is interactive, using digital whiteboards and real-time problem solving. I am STEM-focused and prepare students for WAEC, NECO, JAMB, and university-level courses. All sessions are recorded and shared for revision.',
    subjects: ['Physics', 'Mathematics', 'JAMB Prep', 'WAEC Prep', 'Further Mathematics'],
    levels: ['jss', 'sss', 'waec', 'jamb'],
    teachingMode: ['online'],
    state: 'Bayelsa',
    city: 'Yenagoa',
    hourlyRateNaira: 3000,
    groupRateNaira: 1800,
    trialAvailable: true,
    trialDurationMins: 30,
    yearsExperience: 4,
    languages: ['English'],
    specializations: ['JAMB Preparation', 'WAEC Revision'],
    qualifications: [
      { title: 'B.Eng. Mechanical Engineering', institution: 'Niger Delta University', year: '2019' },
    ],
    rating: 4.5,
    reviewCount: 38,
    totalSessions: 153,
    isVerified: true,
    responseTime: 'Within 3 hours',
  },
  {
    name: 'Ovie Sharon Oteri',
    email: 'ovie.oteri@tutors.naijaandoverseas.com',
    phone: '+234 805 444 0030',
    headline: 'English, Literature & CRS — Warri Home Tutor',
    bio: 'I am a passionate English and Literature tutor offering home lessons in Warri and environs. I help students improve their reading, writing, and comprehension skills. I prepare SS3 students for WAEC English Language and Literature in English with detailed essay coaching and past question analysis. I am very patient and supportive.',
    subjects: ['English Language', 'Literature in English', 'Christian Religious Studies'],
    levels: ['jss', 'sss', 'waec', 'neco'],
    teachingMode: ['in-person'],
    state: 'Delta',
    city: 'Warri',
    hourlyRateNaira: 2500,
    groupRateNaira: 1500,
    trialAvailable: true,
    trialDurationMins: 30,
    yearsExperience: 5,
    languages: ['English'],
    specializations: ['WAEC Revision', 'NECO Preparation'],
    qualifications: [
      { title: 'B.A. English & Literary Studies', institution: 'Delta State University', year: '2018' },
    ],
    rating: 4.4,
    reviewCount: 29,
    totalSessions: 116,
    isVerified: false,
    responseTime: 'Within 24 hours',
  },
  {
    name: 'Emeka Sunday Briggs',
    email: 'emeka.briggs@tutors.naijaandoverseas.com',
    phone: '+234 806 444 0031',
    headline: 'Economics & Financial Accounting Expert — Port Harcourt',
    bio: 'I am a professional accountant and Business Education tutor with 8 years of experience. I teach Economics and Financial Accounting for SSS students and work professionals looking to upskill. My sessions are practical and real-world oriented, connecting textbook content to business realities. I have excellent results in both WAEC and ICAN foundation exams.',
    subjects: ['Economics', 'Financial Accounting', 'Commerce', 'WAEC Prep'],
    levels: ['sss', 'waec', 'neco', 'university'],
    teachingMode: ['online', 'in-person'],
    state: 'Rivers',
    city: 'Port Harcourt',
    hourlyRateNaira: 3500,
    groupRateNaira: 2000,
    trialAvailable: true,
    trialDurationMins: 30,
    yearsExperience: 8,
    languages: ['English'],
    specializations: ['WAEC Revision'],
    qualifications: [
      { title: 'B.Sc. Accounting', institution: 'University of Port Harcourt', year: '2015' },
      { title: 'ACA (Associate Chartered Accountant)', institution: 'ICAN', year: '2019' },
    ],
    rating: 4.7,
    reviewCount: 57,
    totalSessions: 228,
    isVerified: true,
    responseTime: 'Within 3 hours',
  },
  {
    name: 'Favour Chidinma Dibia',
    email: 'favour.dibia@tutors.naijaandoverseas.com',
    phone: '+234 807 444 0032',
    headline: 'IELTS Coach & English Language Tutor — Port Harcourt',
    bio: 'I am an IELTS coach and English language specialist with a passion for helping Nigerians achieve their international education and career goals. I offer IELTS preparation (Academic and General Training) with a focus on all four modules. I also coach professionals for business English and workplace communication.',
    subjects: ['IELTS', 'English Language', 'Literature in English'],
    levels: ['sss', 'university', 'adult'],
    teachingMode: ['online'],
    state: 'Rivers',
    city: 'Port Harcourt',
    hourlyRateNaira: 6000,
    groupRateNaira: 3500,
    trialAvailable: true,
    trialDurationMins: 45,
    yearsExperience: 6,
    languages: ['English', 'Igbo'],
    specializations: ['IELTS Coaching'],
    qualifications: [
      { title: 'M.A. Applied Linguistics', institution: 'University of Port Harcourt', year: '2017' },
    ],
    rating: 4.8,
    reviewCount: 63,
    totalSessions: 250,
    isVerified: true,
    responseTime: 'Within 1 hour',
  },

  // ── OGUN / SOUTH-WEST (5) ────────────────────────────────────────────────
  {
    name: 'Taiwo Olanrewaju Alabi',
    email: 'taiwo.alabi@tutors.naijaandoverseas.com',
    phone: '+234 802 555 0033',
    headline: 'Mathematics & Further Maths Tutor — Abeokuta\'s Best',
    bio: 'I have taught Mathematics and Further Mathematics in Ogun State for 7 years. My students regularly top their school classes after sessions with me. I offer both online classes and home visits around Abeokuta and Sagamu. My crash courses before WAEC and JAMB are particularly popular and effective.',
    subjects: ['Mathematics', 'Further Mathematics', 'JAMB Prep', 'WAEC Prep'],
    levels: ['jss', 'sss', 'waec', 'jamb'],
    teachingMode: ['online', 'in-person'],
    state: 'Ogun',
    city: 'Abeokuta',
    hourlyRateNaira: 3500,
    groupRateNaira: 2000,
    trialAvailable: true,
    trialDurationMins: 30,
    yearsExperience: 7,
    languages: ['English', 'Yoruba'],
    specializations: ['JAMB Preparation', 'WAEC Revision'],
    qualifications: [
      { title: 'B.Sc. Mathematics', institution: 'Olabisi Onabanjo University', year: '2015' },
    ],
    rating: 4.7,
    reviewCount: 60,
    totalSessions: 238,
    isVerified: true,
    responseTime: 'Within 3 hours',
  },
  {
    name: 'Ngozi Adeyemi Clarke',
    email: 'ngozi.clarke@tutors.naijaandoverseas.com',
    phone: '+234 803 555 0034',
    headline: 'Physics, Chemistry & Biology — Science Made Easy',
    bio: 'I am a Science teacher with a gift for making difficult concepts easy and memorable. I use creative mnemonics, colorful diagrams, and structured experiments to teach Physics, Chemistry, and Biology. I have 6 years of tutoring experience in Ogun State and prepare students for WAEC and NECO examinations.',
    subjects: ['Physics', 'Chemistry', 'Biology', 'WAEC Prep', 'NECO Prep'],
    levels: ['sss', 'waec', 'neco'],
    teachingMode: ['in-person'],
    state: 'Ogun',
    city: 'Sagamu',
    hourlyRateNaira: 3000,
    groupRateNaira: 1800,
    trialAvailable: true,
    trialDurationMins: 30,
    yearsExperience: 6,
    languages: ['English', 'Igbo', 'Yoruba'],
    specializations: ['WAEC Revision', 'NECO Preparation'],
    qualifications: [
      { title: 'B.Sc. Physics', institution: 'Olabisi Onabanjo University', year: '2017' },
    ],
    rating: 4.6,
    reviewCount: 43,
    totalSessions: 172,
    isVerified: true,
    responseTime: 'Within 3 hours',
  },
  {
    name: 'Tokunbo Adewale Oluwa',
    email: 'tokunbo.oluwa@tutors.naijaandoverseas.com',
    phone: '+234 804 555 0035',
    headline: 'Government, History & Literature Online Tutor',
    bio: 'I am a History and Government teacher offering engaging online lessons for SSS students. I have a talent for making historical events and government processes interesting through storytelling and current affairs integration. I prepare students for WAEC and NECO with focused past question practice and model answers.',
    subjects: ['Government', 'History', 'Literature in English', 'WAEC Prep'],
    levels: ['jss', 'sss', 'waec'],
    teachingMode: ['online'],
    state: 'Ogun',
    city: 'Ijebu-Ode',
    hourlyRateNaira: 2500,
    groupRateNaira: 1500,
    trialAvailable: true,
    trialDurationMins: 30,
    yearsExperience: 5,
    languages: ['English', 'Yoruba'],
    specializations: ['WAEC Revision'],
    qualifications: [
      { title: 'B.A. History & International Studies', institution: 'Olabisi Onabanjo University', year: '2018' },
    ],
    rating: 4.4,
    reviewCount: 32,
    totalSessions: 128,
    isVerified: false,
    responseTime: 'Within 24 hours',
  },
  {
    name: 'Funmi Biodun Adeosun',
    email: 'funmi.adeosun@tutors.naijaandoverseas.com',
    phone: '+234 805 555 0036',
    headline: 'Primary School Tutor — Maths, English & Science Specialist',
    bio: 'I am a dedicated primary school tutor with 4 years of experience helping children in Ota and its environs. I teach all core primary subjects with a special focus on Maths, English, and Basic Science. I use child-centred teaching methods that make learning natural and enjoyable. I work closely with parents and provide weekly progress updates.',
    subjects: ['Mathematics', 'English Language', 'Basic Science', 'Quantitative Reasoning', 'Verbal Reasoning'],
    levels: ['primary', 'jss'],
    teachingMode: ['in-person'],
    state: 'Ogun',
    city: 'Ota',
    hourlyRateNaira: 2000,
    groupRateNaira: 1200,
    trialAvailable: true,
    trialDurationMins: 30,
    yearsExperience: 4,
    languages: ['English', 'Yoruba'],
    specializations: ['Common Entrance Prep'],
    qualifications: [
      { title: 'NCE (Primary Education)', institution: 'Tai Solarin College of Education', year: '2019' },
    ],
    rating: 4.7,
    reviewCount: 33,
    totalSessions: 132,
    isVerified: false,
    responseTime: 'Within 24 hours',
  },
  {
    name: 'Yetunde Afolabi Ojo',
    email: 'yetunde.ojo@tutors.naijaandoverseas.com',
    phone: '+234 806 555 0037',
    headline: 'Fine Arts, Technical Drawing & Creative Arts Tutor',
    bio: 'I am an artist and Art teacher offering tutoring in Fine Arts, Technical Drawing, and Basic Technology in Abeokuta. I help students discover and develop their creative talents while preparing them for WAEC Art examinations. My sessions are hands-on and studio-style. I provide art materials guidance and portfolio development for advanced students.',
    subjects: ['Fine Arts', 'Technical Drawing', 'Basic Technology'],
    levels: ['jss', 'sss', 'waec'],
    teachingMode: ['in-person'],
    state: 'Ogun',
    city: 'Abeokuta',
    hourlyRateNaira: 2500,
    groupRateNaira: 1500,
    trialAvailable: true,
    trialDurationMins: 30,
    yearsExperience: 6,
    languages: ['English', 'Yoruba'],
    specializations: ['WAEC Revision'],
    qualifications: [
      { title: 'B.A. Fine & Applied Arts', institution: 'Obafemi Awolowo University', year: '2016' },
    ],
    rating: 4.6,
    reviewCount: 26,
    totalSessions: 104,
    isVerified: true,
    responseTime: 'Within 24 hours',
  },

  // ── ENUGU / SOUTH-EAST (5) ──────────────────────────────────────────────
  {
    name: 'Obioma Chukwuemeka Agu',
    email: 'obioma.agu@tutors.naijaandoverseas.com',
    phone: '+234 802 666 0038',
    headline: 'Commerce, Financial Accounting & Economics — Enugu',
    bio: 'I am a Business Education teacher and professional tutor with 8 years of experience in Enugu State. I have helped hundreds of SSS students excel in Commerce, Financial Accounting, and Economics for WAEC and NECO. My sessions are structured with detailed notes, solved past questions, and regular assessment tests.',
    subjects: ['Commerce', 'Financial Accounting', 'Economics', 'WAEC Prep', 'NECO Prep'],
    levels: ['sss', 'waec', 'neco'],
    teachingMode: ['online', 'in-person'],
    state: 'Enugu',
    city: 'Enugu',
    hourlyRateNaira: 3000,
    groupRateNaira: 1800,
    trialAvailable: true,
    trialDurationMins: 30,
    yearsExperience: 8,
    languages: ['English', 'Igbo'],
    specializations: ['WAEC Revision', 'NECO Preparation'],
    qualifications: [
      { title: 'B.Sc. Accounting', institution: 'University of Nigeria, Nsukka', year: '2014' },
    ],
    rating: 4.7,
    reviewCount: 55,
    totalSessions: 220,
    isVerified: true,
    responseTime: 'Within 3 hours',
  },
  {
    name: 'Adaeze Nkechi Onuorah',
    email: 'adaeze.onuorah@tutors.naijaandoverseas.com',
    phone: '+234 803 666 0039',
    headline: 'Igbo Language & English Literature Tutor — All Levels',
    bio: 'I am one of the few tutors in Enugu who specializes in Igbo Language for both Primary and Secondary school students. I also teach English Language and Literature. I am deeply passionate about preserving and teaching our indigenous language while helping students succeed in their examinations. My lessons are fun, cultural, and deeply educational.',
    subjects: ['Igbo', 'English Language', 'Literature in English', 'Verbal Reasoning'],
    levels: ['primary', 'jss', 'sss', 'waec'],
    teachingMode: ['in-person'],
    state: 'Enugu',
    city: 'Enugu',
    hourlyRateNaira: 2500,
    groupRateNaira: 1500,
    trialAvailable: true,
    trialDurationMins: 30,
    yearsExperience: 7,
    languages: ['English', 'Igbo'],
    specializations: ['WAEC Revision'],
    qualifications: [
      { title: 'B.A. Igbo & English', institution: 'University of Nigeria, Nsukka', year: '2015' },
    ],
    rating: 4.6,
    reviewCount: 35,
    totalSessions: 140,
    isVerified: true,
    responseTime: 'Within 24 hours',
  },
  {
    name: 'Uchenna Kelechi Nwachukwu',
    email: 'uchenna.nwachukwu@tutors.naijaandoverseas.com',
    phone: '+234 804 666 0040',
    headline: 'Mathematics, Physics & Further Maths — Online Nationwide',
    bio: 'I teach Mathematics, Physics, and Further Mathematics online to students across Nigeria from Onitsha. I use a digital whiteboard and interactive tools to make abstract Science and Maths topics visual and understandable. I have strong WAEC and JAMB results to show. My sessions are focused, fast-paced, and results-driven.',
    subjects: ['Mathematics', 'Physics', 'Further Mathematics', 'JAMB Prep', 'WAEC Prep'],
    levels: ['sss', 'waec', 'jamb'],
    teachingMode: ['online'],
    state: 'Anambra',
    city: 'Onitsha',
    hourlyRateNaira: 3500,
    groupRateNaira: 2000,
    trialAvailable: true,
    trialDurationMins: 30,
    yearsExperience: 5,
    languages: ['English', 'Igbo'],
    specializations: ['JAMB Preparation', 'WAEC Revision'],
    qualifications: [
      { title: 'B.Sc. Mechanical Engineering', institution: 'Nnamdi Azikiwe University', year: '2018' },
    ],
    rating: 4.7,
    reviewCount: 49,
    totalSessions: 196,
    isVerified: true,
    responseTime: 'Within 3 hours',
  },
  {
    name: 'Chinyere Chinelo Odu',
    email: 'chinyere.odu@tutors.naijaandoverseas.com',
    phone: '+234 805 666 0041',
    headline: 'Biology, Agric Science & Home Economics — Aba, Abia State',
    bio: 'I offer in-home tutoring in Biology, Agricultural Science, and Home Economics for SSS students in Aba. My lessons are detailed and student-friendly. I have a gentle teaching approach that helps anxious students build confidence. I prepare students thoroughly for WAEC and NECO with focused topic revision and past question practice.',
    subjects: ['Biology', 'Agricultural Science', 'WAEC Prep', 'NECO Prep'],
    levels: ['sss', 'waec', 'neco'],
    teachingMode: ['in-person'],
    state: 'Abia',
    city: 'Aba',
    hourlyRateNaira: 2500,
    groupRateNaira: 1500,
    trialAvailable: true,
    trialDurationMins: 30,
    yearsExperience: 4,
    languages: ['English', 'Igbo'],
    specializations: ['WAEC Revision', 'NECO Preparation'],
    qualifications: [
      { title: 'B.Sc. Agricultural Science', institution: 'Abia State University', year: '2019' },
    ],
    rating: 4.4,
    reviewCount: 24,
    totalSessions: 96,
    isVerified: false,
    responseTime: 'Within 24 hours',
  },
  {
    name: 'Ikechukwu Emmanuel Obi',
    email: 'ikechukwu.obi@tutors.naijaandoverseas.com',
    phone: '+234 806 666 0042',
    headline: 'Computer Science & Mathematics — University-Level Support',
    bio: 'I am a Computer Science graduate offering tutoring in Computer Science, Programming, and Mathematics for both secondary school students and university freshmen. I specialize in helping first-year university students who are struggling with discrete mathematics, data structures, and introductory programming. My sessions are technical, hands-on, and practical.',
    subjects: ['Computer Science', 'Mathematics', 'Python', 'WAEC Prep'],
    levels: ['sss', 'waec', 'university'],
    teachingMode: ['online'],
    state: 'Enugu',
    city: 'Enugu',
    hourlyRateNaira: 4000,
    groupRateNaira: 2200,
    trialAvailable: true,
    trialDurationMins: 30,
    yearsExperience: 3,
    languages: ['English', 'Igbo'],
    specializations: ['Coding & Tech Skills', 'WAEC Revision'],
    qualifications: [
      { title: 'B.Sc. Computer Science', institution: 'University of Nigeria, Nsukka', year: '2022' },
    ],
    rating: 4.5,
    reviewCount: 27,
    totalSessions: 108,
    isVerified: true,
    responseTime: 'Within 3 hours',
  },

  // ── OYO / IBADAN (4) ────────────────────────────────────────────────────
  {
    name: 'Biodun Olatunji Adeniyi',
    email: 'biodun.adeniyi@tutors.naijaandoverseas.com',
    phone: '+234 802 777 0043',
    headline: 'Mathematics & Physics Tutor — UI & Ibadan Expert',
    bio: 'I am a Mathematics and Physics tutor in Ibadan with strong connections to the University of Ibadan community. I prepare SS students for WAEC, JAMB, and Post-UTME examinations with high success rates. My teaching is thorough, well-paced, and supported by comprehensive study materials. I offer both online and home visit sessions across Ibadan.',
    subjects: ['Mathematics', 'Physics', 'Further Mathematics', 'JAMB Prep', 'WAEC Prep'],
    levels: ['sss', 'waec', 'jamb'],
    teachingMode: ['online', 'in-person'],
    state: 'Oyo',
    city: 'Ibadan',
    hourlyRateNaira: 3500,
    groupRateNaira: 2000,
    trialAvailable: true,
    trialDurationMins: 30,
    yearsExperience: 7,
    languages: ['English', 'Yoruba'],
    specializations: ['JAMB Preparation', 'WAEC Revision', 'Post-UTME Coaching'],
    qualifications: [
      { title: 'B.Sc. Mathematics', institution: 'University of Ibadan', year: '2015' },
    ],
    rating: 4.8,
    reviewCount: 73,
    totalSessions: 292,
    isVerified: true,
    responseTime: 'Within 1 hour',
  },
  {
    name: 'Kemi Adewale Ogunleye',
    email: 'kemi.ogunleye@tutors.naijaandoverseas.com',
    phone: '+234 803 777 0044',
    headline: 'English, Literature & Yoruba Language Tutor — Ibadan',
    bio: 'I am a Language Arts teacher offering tutoring in English Language, Literature in English, and Yoruba Language in Ibadan. I teach students from primary school age to SSS with equal skill and passion. I specialize in building reading and comprehension skills, creative writing, and oral communication. I am also one of the rare tutors who can teach Yoruba formally for WAEC.',
    subjects: ['English Language', 'Literature in English', 'Yoruba', 'Verbal Reasoning'],
    levels: ['primary', 'jss', 'sss', 'waec'],
    teachingMode: ['in-person'],
    state: 'Oyo',
    city: 'Ibadan',
    hourlyRateNaira: 2500,
    groupRateNaira: 1500,
    trialAvailable: true,
    trialDurationMins: 30,
    yearsExperience: 8,
    languages: ['English', 'Yoruba'],
    specializations: ['WAEC Revision'],
    qualifications: [
      { title: 'B.A. English', institution: 'University of Ibadan', year: '2014' },
    ],
    rating: 4.7,
    reviewCount: 61,
    totalSessions: 244,
    isVerified: true,
    responseTime: 'Within 3 hours',
  },
  {
    name: 'Femi Olawale Ogundele',
    email: 'femi.ogundele@tutors.naijaandoverseas.com',
    phone: '+234 804 777 0045',
    headline: 'Chemistry & Biology Online Tutor — Ibadan Based',
    bio: 'I am a Chemistry and Biology tutor offering affordable online lessons for SSS students. I use Zoom and Google Classroom to deliver structured sessions with assignments and tests. My students achieve remarkable improvements in their understanding of organic chemistry, genetics, and cell biology. I am available on weekdays and weekends.',
    subjects: ['Chemistry', 'Biology', 'WAEC Prep', 'JAMB Prep'],
    levels: ['sss', 'waec', 'jamb'],
    teachingMode: ['online'],
    state: 'Oyo',
    city: 'Ibadan',
    hourlyRateNaira: 3000,
    groupRateNaira: 1800,
    trialAvailable: true,
    trialDurationMins: 30,
    yearsExperience: 4,
    languages: ['English', 'Yoruba'],
    specializations: ['WAEC Revision', 'JAMB Preparation'],
    qualifications: [
      { title: 'B.Sc. Biochemistry', institution: 'University of Ibadan', year: '2019' },
    ],
    rating: 4.5,
    reviewCount: 39,
    totalSessions: 157,
    isVerified: true,
    responseTime: 'Within 3 hours',
  },
  {
    name: 'Toyin Adeola Olatunde',
    email: 'toyin.olatunde@tutors.naijaandoverseas.com',
    phone: '+234 805 777 0046',
    headline: 'Economics, Commerce & Financial Accounting — WAEC & NECO',
    bio: 'I teach Business Education subjects — Economics, Commerce, and Financial Accounting — for SS2 and SS3 students preparing for WAEC and NECO. My approach is systematic: I work through the entire syllabus topic by topic before intensive revision and past question practice in the final weeks. I am available online and for home lessons in Ibadan.',
    subjects: ['Economics', 'Commerce', 'Financial Accounting', 'WAEC Prep', 'NECO Prep'],
    levels: ['sss', 'waec', 'neco'],
    teachingMode: ['online', 'in-person'],
    state: 'Oyo',
    city: 'Ibadan',
    hourlyRateNaira: 2500,
    groupRateNaira: 1500,
    trialAvailable: true,
    trialDurationMins: 30,
    yearsExperience: 5,
    languages: ['English', 'Yoruba'],
    specializations: ['WAEC Revision', 'NECO Preparation'],
    qualifications: [
      { title: 'B.Sc. Business Administration', institution: 'University of Ibadan', year: '2018' },
    ],
    rating: 4.5,
    reviewCount: 34,
    totalSessions: 137,
    isVerified: false,
    responseTime: 'Within 24 hours',
  },

  // ── EDO / DELTA / CROSS RIVER / OTHERS (8) ──────────────────────────────
  {
    name: 'Eghosa Emmanuel Osaghae',
    email: 'eghosa.osaghae@tutors.naijaandoverseas.com',
    phone: '+234 802 888 0047',
    headline: 'Mathematics & Further Maths — Benin City Online Expert',
    bio: 'I am an Mathematics and Further Mathematics tutor offering online classes from Benin City. My teaching covers the complete SS1–SS3 and WAEC/JAMB syllabus. I use real-time digital whiteboards and step-by-step approach for every topic. My students average 80% pass rate in WAEC Mathematics. I also offer intensive pre-exam preparation packages.',
    subjects: ['Mathematics', 'Further Mathematics', 'JAMB Prep', 'WAEC Prep'],
    levels: ['jss', 'sss', 'waec', 'jamb'],
    teachingMode: ['online'],
    state: 'Edo',
    city: 'Benin City',
    hourlyRateNaira: 3500,
    groupRateNaira: 2000,
    trialAvailable: true,
    trialDurationMins: 30,
    yearsExperience: 6,
    languages: ['English'],
    specializations: ['JAMB Preparation', 'WAEC Revision'],
    qualifications: [
      { title: 'B.Sc. Mathematics', institution: 'University of Benin', year: '2016' },
    ],
    rating: 4.7,
    reviewCount: 53,
    totalSessions: 212,
    isVerified: true,
    responseTime: 'Within 3 hours',
  },
  {
    name: 'Eseosa Blessing Evbuoma',
    email: 'eseosa.evbuoma@tutors.naijaandoverseas.com',
    phone: '+234 803 888 0048',
    headline: 'English Language & Literature — Benin City Home Tutor',
    bio: 'I offer home tutoring in English Language and Literature in English for JSS and SSS students in Benin City and environs. I am particularly skilled at helping students who struggle with essay writing and comprehension passages. My calm and encouraging teaching style helps even the most hesitant students gain confidence and improve their scores.',
    subjects: ['English Language', 'Literature in English', 'Verbal Reasoning'],
    levels: ['jss', 'sss', 'waec'],
    teachingMode: ['in-person'],
    state: 'Edo',
    city: 'Benin City',
    hourlyRateNaira: 2500,
    groupRateNaira: 1500,
    trialAvailable: true,
    trialDurationMins: 30,
    yearsExperience: 4,
    languages: ['English'],
    specializations: ['WAEC Revision'],
    qualifications: [
      { title: 'B.A. English & Literary Studies', institution: 'University of Benin', year: '2019' },
    ],
    rating: 4.4,
    reviewCount: 27,
    totalSessions: 108,
    isVerified: false,
    responseTime: 'Within 24 hours',
  },
  {
    name: 'Ifeoma Grace Anibueze',
    email: 'ifeoma.anibueze@tutors.naijaandoverseas.com',
    phone: '+234 804 888 0049',
    headline: 'Chemistry, Biology & Agric Science Tutor — Asaba & Online',
    bio: 'I am a Science teacher offering tutoring in Chemistry, Biology, and Agricultural Science from Asaba. I teach online students nationwide and also offer home lessons in the Asaba area. My students frequently report dramatic improvements in their Science grades. I use colorful diagrams, mnemonics, and past question analysis in every class.',
    subjects: ['Chemistry', 'Biology', 'Agricultural Science', 'WAEC Prep', 'NECO Prep'],
    levels: ['sss', 'waec', 'neco'],
    teachingMode: ['online', 'in-person'],
    state: 'Delta',
    city: 'Asaba',
    hourlyRateNaira: 3000,
    groupRateNaira: 1800,
    trialAvailable: true,
    trialDurationMins: 30,
    yearsExperience: 5,
    languages: ['English', 'Igbo'],
    specializations: ['WAEC Revision', 'NECO Preparation'],
    qualifications: [
      { title: 'B.Sc. Biology', institution: 'Delta State University', year: '2018' },
    ],
    rating: 4.6,
    reviewCount: 41,
    totalSessions: 164,
    isVerified: true,
    responseTime: 'Within 3 hours',
  },
  {
    name: 'Ekeng Sunday Etim',
    email: 'ekeng.etim@tutors.naijaandoverseas.com',
    phone: '+234 805 888 0050',
    headline: 'Mathematics, Physics & JAMB Prep — Calabar Online Tutor',
    bio: 'I am a Mathematics and Physics tutor based in Calabar offering online classes to students across Nigeria. I focus on helping students who are struggling with these subjects and need a patient, step-by-step guide. I have experience preparing students for JAMB, WAEC, and NECO. My sessions are affordable, focused, and results-oriented.',
    subjects: ['Mathematics', 'Physics', 'JAMB Prep', 'WAEC Prep', 'Basic Science'],
    levels: ['jss', 'sss', 'waec', 'jamb'],
    teachingMode: ['online'],
    state: 'Cross River',
    city: 'Calabar',
    hourlyRateNaira: 3000,
    groupRateNaira: 1800,
    trialAvailable: true,
    trialDurationMins: 30,
    yearsExperience: 4,
    languages: ['English'],
    specializations: ['JAMB Preparation', 'WAEC Revision'],
    qualifications: [
      { title: 'B.Sc. Physics', institution: 'University of Calabar', year: '2020' },
    ],
    rating: 4.5,
    reviewCount: 32,
    totalSessions: 128,
    isVerified: true,
    responseTime: 'Within 3 hours',
  },
];

const seedTutors = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log('✅ MongoDB connected');

    // Clear existing tutor data only
    await TutorReview.deleteMany({});
    await TutorProfile.deleteMany({});
    console.log('🗑️  Cleared existing tutor profiles and reviews');

    // Remove previously seeded tutor users (identified by email pattern)
    await User.deleteMany({ email: { $regex: '@tutors.naijaandoverseas.com$' } });
    console.log('🗑️  Cleared existing seed tutor users');

    let created = 0;

    for (const t of TUTORS) {
      // Create user account for the tutor
      const user = await User.create({
        name: t.name,
        email: t.email,
        password: 'Tutor@NaijaOverseas2026',
        role: 'student',
        phone: t.phone,
        country: 'Nigeria',
        isVerified: true,
      });

      // Create tutor profile
      await TutorProfile.create({
        user: user._id,
        displayName: t.name,
        headline: t.headline,
        bio: t.bio,
        subjects: t.subjects,
        levels: t.levels,
        teachingMode: t.teachingMode,
        state: t.state,
        city: t.city,
        hourlyRateNaira: t.hourlyRateNaira,
        groupRateNaira: t.groupRateNaira,
        trialAvailable: t.trialAvailable,
        trialDurationMins: t.trialDurationMins,
        yearsExperience: t.yearsExperience,
        languages: t.languages,
        specializations: t.specializations,
        qualifications: t.qualifications,
        rating: t.rating,
        reviewCount: t.reviewCount,
        totalSessions: t.totalSessions,
        isVerified: t.isVerified,
        isActive: true,
        responseTime: t.responseTime,
      });

      created++;
      console.log(`   ✅ [${created}] ${t.name} — ${t.state} — ${t.subjects.slice(0, 2).join(', ')}`);
    }

    console.log(`\n🎉 Successfully created ${created} tutor profiles!`);
    console.log('\nSample tutor login:');
    console.log('Email:    chidi.okafor@tutors.naijaandoverseas.com');
    console.log('Password: Tutor@NaijaOverseas2026');

    process.exit(0);
  } catch (err) {
    console.error('❌ Seed error:', err.message);
    process.exit(1);
  }
};

seedTutors();
